### ISSUE TITLE
SkipWeatherOnSleep Option won't turn off

### ISSUE THREAD

**Issue by Thalomin** [someaddons/weathersettings#1]
By default the mod turns off "skipping weather by sleeping". It does this by turning off the "DoWeatherCycle" game rule. But it uses this code:

        if (!WeatherSettingsMod.config.getCommonConfig().skipWeatherOnSleep)
        {
            server.getGameRules().getRule(GameRules.RULE_WEATHER_CYCLE).set(false, server);
        }

So, when the server starts, it checks the SkipWeatherOnSleep config opion. If that is FALSE, it sets  DoWeatherCycle to FALSE.

HOWEVER, what it doesn't do, it set DoWeatherCycle to TRUE if the confile option is set to TRUE.

This means that when you first started the server with the mod installed, it creates the default config and turns off the weather cycle. And then, once you update the config file, IT NEVER TURNS IT BACK ON!

**Comment by someaddons** [comment]
fixed^^
