### ISSUE TITLE
Suggestion: Add values to configure minimum and maximum durations (to enable some kind of random duration times)

### ISSUE THREAD

**Issue by Maypul** [someaddons/weathersettings#3]
Hello!
The mod looks like something I need in my pack as without it I do have some issues with vanilla weather. I am on 1.19.2 and would love to see options to somewhat make the rain more "randomized". It does not seems like the weight is cutting it.

**Comment by someaddons** [comment]
it actually does random already, it goes from 0.75x duration up to 1.25x duration randomly

**Comment by Maypul** [comment]
That's actually cool. I assume I can also add multiple entries of the same weather with different values? I'll close the issue then. Thanks.
